### ISSUE TITLE
Create basic framework

### ISSUE THREAD

**Issue by terrifricker** [chingu-voyages/v43-tier1-team-08#14]
Create html framework with css including semantic html for

- [x] Title of website #23 
- [x] Short description #32
- [x] Game instructions #29
- [x] Title of story #24
- [x] Empty section for form #27
- [x] Empty section for story template #28
- [ ] Button for returning to top #25
- [x] Link in footer to GitHub repository #26

**Comment by mmsaki** [comment]
hey @AustonBoyd  @terrifricker, nice work on this issue #14, very detailed. However, I think this issue has too many specifications. All those features have different levels of complexity which might be easier to separate them by that. Any feedback if it would be nice to split this work to separate a separate issue? or could just be one or two at a time.

**Comment by mmsaki** [comment]
@AustonBoyd incase you already started I just wanted to add to keep in mind the specification from this [Figma file](https://www.figma.com/file/MuxLPW61ocqCoqZUyLA84Z/team8?node-id=0%3A1&t=5apvQsRLePGew7bW-1) for context just so it's clear on how you should approach it.
 
- You can view the CSS styling straight from Figma which is usually helpful.

<img width="497" alt="Screenshot 2023-03-16 at 2 02 06 PM" src="https://user-images.githubusercontent.com/98189596/225763326-38a863c1-179d-4f0b-8777-edb3f466a5bf.png">

@AustonBoyd please let me know if this is helpful and if the tasks assigned to you are too many

**Comment by terrifricker** [comment]
What is our plan?  This issue is fair game to anyone on the team by Saturday morning, so it can be finished within the sprint?

**Comment by AustonBoyd** [comment]
I'm working on it, as previously stated.

**Comment by AustonBoyd** [comment]
Regarding Issue #25 ;
Are we going to divide each story up by pages, or will we incorporate all stories into a single page that the user will navigate? Thanks!
